### PR TITLE
Enable ingress for DCS Prod

### PR DESCRIPTION
**Pull request by Krenair**

### CODE REVIEW

**Comment by Krenair** [comment]
@bjgill: I don't think it will, build already has ingress and that's set up in the list entry below the one we're modifying.

**Comment by bjgill** [comment]
Sorry. I was getting confused. You are quite right. We will also need to set `ingress: true` in doc-checking itself.

Happy if we've got the OK from Cyber/IA.

**Comment by Krenair** [comment]
Yeah I think we're just waiting for it in writing at this point. Not merging until then of course.

**Comment by Krenair** [comment]
I'm told now that IA has formally given approval, let's do this?

**Pull request merged**
